### ISSUE TITLE
no title

### ISSUE THREAD

**Issue by wxl112** [SHU-FLYMAN/Usful_Linear_Algebra#1]
我想问一下大佬你做的是基于图像的三维重建技术还是什么？

**Comment by SHU-FLYMAN** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我主要从事基于结构光的三维重建，此外SLAM也略有涉及，之前也自己复现过几个深度学习的开源demo，参加过这方面比赛，获得过奖。因为一路走下来，发现这方面教程还是挺少的，所以有这个想法，目前正在逐渐更新这方面的笔记跟教程，更新速度会有点慢，但力求质量。
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                曹建斌
                            
                    
                        
                            
                                    1011836423@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/18/2020 16:04，Lucas.hood<notifications@github.com> wrote： 




我想问一下大佬你做的是基于图像的三维重建技术还是什么？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wxl112** [comment]
em,怎么说呢我是一个外行从事故障诊断和机器学习，深度学习研究。看到你这个研究方向很是喜欢也很欣赏，希望自己能慢慢向你学习。

**Comment by SHU-FLYMAN** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    欢迎！我一定努力更新！
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                曹建斌
                            
                    
                        
                            
                                    1011836423@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/18/2020 16:14，Lucas.hood<notifications@github.com> wrote： 




em,怎么说呢我是一个外行从事故障诊断和机器学习，深度学习研究。看到你这个研究方向很是喜欢也很欣赏，希望自己能慢慢向你学习。



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
